swagger: '2.0'
info:
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Research team
    url: https://www.mediawiki.org/wiki/Wikimedia_Research
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
            headers:
              user-agent: '*'
              disallow: '/'
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: doc from root
          request:
            query:
              doc: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404
  # from routes/translation.js
  /{domain}/v1/translation/articles/{source}{/seed}:
    get:
      tags:
        - Recommend
      summary: Recommend missing articles
      description: |
        Recommends articles to be translated from the source
        to the domain language.
        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      produces:
        - applicaiton/json
      parameters:
        - name: source
          in: path
          description: The source language code
          type: string
          required: true
        - name: domain
          in: path
          description: The target domain
          type: string
          required: true
        - name: seed
          in: path
          description: The article to use as a search seed
          type: string
          required: false
        - name: count
          in: query
          description: The max number of articles to return
          type: int
          required: false
          default: 24
      x-amples:
        - title: normal source and target
          request:
            params:
              source: en
              domain: de.wikipedia.org
          response:
            status: 200
            headers:
              content-type: application/json
        - title: normal source and target with seed
          request:
            params:
              source: en
              domain: de.wikipedia.org
              seed: Apple
          response:
            status: 200
            headers:
              content-type: application/json
        - title: bad source
          request:
            params:
              source: qqq
              domain: de.wikipedia.org
          response:
            status: 504
            headers:
              content-type: application/json
        - title: bad seed
          request:
            params:
              source: en
              domain: de.wikipedia.org
              seed: thishsouldnotreturnanyresultsfromthesearchapi
          response:
            status: 404
            headers:
              content-type: application/json
        - title: invalid count
          request:
            params:
              source: en
              domain: de.wikipedia.org
            query:
              count: -123
          response:
            status: 400
