* Article creation — morelike
  The 'morelike' API helps discover articles that are similar to a seed
  article, but are missing from the Wikipedia and are present in other
  language Wikipedias.

  For example, if we're interested in articles similar to 'Kitob' (Book)
  in uzwiki, the results of the API may look like this:

  | wikidata_id | normalized_rank |
  |-------------+-------|
  | "Q83357"    |   0.5 |
  | "Q82"       |  0.45 |
  | ...         |       |

  Here, we can see that Wikidata items Q83357 (Origami) and Q82
  (Printer) don't have sitelinks to uzwiki and are being recommended by
  the API. If these articles are created in uzwiki, the API is
  suggesting that "Origami" article would receive a higher number of
  page views than the "Printer" article.
** Data
   Wikidata ID and normalized rank data used in the API is generated by [[https://gerrit.wikimedia.org/r/#/admin/projects/research/article-recommender][article
   recommender]] and is imported into MySQL by [[https://gerrit.wikimedia.org/r/#/admin/projects/research/article-recommender/deploy][article-recommender/deploy]].

   Normalized_rank is the normalized rank of the article had it been
   created six months prior to generating data. Article's normalized
   rank is its rank when sorted in increasing order of page view counts
   and divided by the total number of articles in Wikipedia for that
   language.

   Two MySQL tables are used for storing data: `language` and
   `article_recommendation`. Article recommendation normalized ranks are
   specific to source and target language pairs. For example, articles
   recommended for creation in uzwiki may come from ruwiki and enwiki
   depending on the existence of data in the database. Here 'uz' is the
   target language, and 'ru' and 'en' are the source languages.
** Algorithm
   1. For a given seed article, find its Wikidata item ID.
   2. For the Wikidata ID from the above step, find similar articles
      using the [[https://en.wikipedia.org/w/api.php?action=help&modules=query%252Bsearch][MediaWiki 'morelike' API]] in the source language
      Wikipedias.
   3. For each similar article's Wikidata ID, find its normalized rank
      from the database and order the results by normalized rank in
      descending order.
   4. The top 10 results are then returned to the user.
